#include <Windows.h>
void DisplaySNAKE();
void DisplayGAME();
void DisplaySNAKEIMG();
void MenuBG();
void GUI();
void GameplayUI();
void ClearScreen();
void StartMenu();
void DisplayInstructions();
void OptionMenu();
void ScoreBox();