#pragma once
#include <Windows.h>
#include <mmsystem.h>

void OpenSound();
void CloseSound();
void OpenMusic();
void PlayMusic();
void PauseMusic();
void StopMusic();
void CloseMusic();
void OpenKey();
void PlayKey();
void StopKey();
void CloseKey();
void OpenEatSound();
void PlayEatSound();
void CloseEatSound();
void OpenDieSound();
void PlayDieSound();
void CloseDieSound();